"""create jobs and metrics tables

Revision ID: c29dbeca38c3
Revises: 
Create Date: 2026-06-24 09:03:36.408586
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29dbeca38c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('result_path', sa.String(length=512), nullable=True),
    sa.Column('algorithm', sa.String(length=32), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_status_expires_at', 'jobs', ['status', 'expires_at'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=32), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_job_id', 'metrics', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metrics_job_id', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('idx_jobs_status_expires_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
